### ISSUE TITLE
Installation not working on Mac OS X 10.15.3

### ISSUE THREAD

**Issue by mhenrixon** [michael-simons/homebrew-seabolt#1]
```
~ brew install michael-simons/homebrew-seabolt/seabolt                                                                                                                                    1 [08:19:54]
==> Installing seabolt from michael-simons/seabolt
==> Downloading https://github.com/neo4j-drivers/seabolt/archive/v1.7.4.tar.gz
Already downloaded: /Users/mhenrixon/Library/Caches/Homebrew/downloads/54f73c543497043c3c1d9c1f5d447ed7c25361ed64473eb6ee4a2c8b13de0b96--seabolt-1.7.4.tar.gz
==> Patching
patching file src/seabolt-cli/src/main.c
==> mkdir build
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/seabolt/1.7.4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE
==> cmake --build . --target install
Last 15 lines from /Users/mhenrixon/Library/Logs/Homebrew/seabolt/03.cmake:
/tmp/seabolt-20200209-28189-1hcuobi/seabolt-1.7.4/src/seabolt-cli/src/main.c:59:1: error: control reaches end of non-void function [-Werror,-Wreturn-type]
}
^
2 errors generated.
gmake[2]: *** [CMakeFiles/seabolt-cli.dir/build.make:66: CMakeFiles/seabolt-cli.dir/src/seabolt-cli/src/main.c.o] Error 1
gmake[2]: Leaving directory '/private/tmp/seabolt-20200209-28189-1hcuobi/seabolt-1.7.4/build'
gmake[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/seabolt-cli.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable bin/seabolt-test
/usr/local/Cellar/cmake/3.16.3/bin/cmake -E cmake_link_script CMakeFiles/seabolt-test.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/seabolt-test.dir/src/seabolt/tests/main.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/seabolt.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-address-set.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-addressing.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-chunking-v1.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-communication.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-connection.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-pooling.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-values.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o  -o bin/seabolt-test  -Wl,-rpath,/tmp/seabolt-20200209-28189-1hcuobi/seabolt-1.7.4/build/lib lib/libseabolt17.a /usr/local/opt/openssl@1.1/lib/libssl.a /usr/local/opt/openssl@1.1/lib/libcrypto.a -lssl -lcrypto
gmake[2]: Leaving directory '/private/tmp/seabolt-20200209-28189-1hcuobi/seabolt-1.7.4/build'
[ 98%] Built target seabolt-test
gmake[1]: Leaving directory '/private/tmp/seabolt-20200209-28189-1hcuobi/seabolt-1.7.4/build'
gmake: *** [Makefile:166: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michael-simons/homebrew-seabolt/issues
```

**Comment by mhenrixon** [comment]
Maybe related to https://github.com/neo4j-drivers/seabolt/pull/80?

**Comment by mhenrixon** [comment]
I tested with building master from https://github.com/gaxuhongyu/seabolt.git and it works like a charm!

**Comment by michael-simons** [comment]
Hey. Thanks for letting me know. I have updated my formula. Would you mind testing? Thanks.

**Comment by mhenrixon** [comment]
Works like a charm @michael-simons ! Thanks for the update

**Comment by michael-simons** [comment]
Thank you! We will bring this into the official seabolt repo as well, but I'm still fighting our CI. The PR builds a currently red for reasons unrelated to the patch.
