### ISSUE TITLE
Installation not working on MacOS Montery (12.0.1)

### ISSUE THREAD

**Issue by SvenAnton** [michael-simons/homebrew-seabolt#6]
The installation fails at 98%. First I tried to install with brew `brew install michael-simons/homebrew-seabolt/seabolt` and got stuck exactly like mentioned in this issue [here](https://github.com/michael-simons/homebrew-seabolt/issues/1). After that I took the source code from [here](https://github.com/gaxuhongyu/seabolt.git), as suggested solution in the mentioned issue, and built it myself using `./make_release`, but the installation still failed at 98%, now with more verbose output.

Currently, I have no ideas how to move forward with debugging this issue.

```
[ 97%] Linking C shared library lib/libseabolt17.dylib
-- Passed
-- Processed
[ 97%] Built target seabolt-shared
[ 98%] Building C object CMakeFiles/seabolt-cli.dir/src/seabolt-cli/src/main.c.o
/Users/user/Downloads/seabolt-1.7/src/seabolt-cli/src/main.c:47:9: error: 'TIME_UTC' macro redefined [-Werror,-Wmacro-redefined]
#define TIME_UTC 0
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/time.h:197:9: note: previous definition is here
#define TIME_UTC        1       /* time elapsed since epoch */
        ^
/Users/user/Downloads/seabolt-1.7/src/seabolt-cli/src/main.c:49:6: error: conflicting types for 'timespec_get'
void timespec_get(struct timespec *ts, int type)
     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/time.h:199:5: note: previous declaration is here
int timespec_get(struct timespec *ts, int base);
    ^
2 errors generated.
make[2]: *** [CMakeFiles/seabolt-cli.dir/src/seabolt-cli/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/seabolt-cli.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by shartep** [comment]
I had same issue

**Comment by fmcyamwe** [comment]
Yup had the same issue and commented out the `timespec_get` function as well as undef TIME_UTC and defined it again in the same vein as [here](https://github.com/aerospike/aerospike-client-c/issues/103) and it worked! 
Also ran earlier into a  `unrecognized instruction mnemonic` error thrown in the `{ CATCH_TRAP(); }` method of the `tests/catch.hpp` file but fixed it by adding the [following](https://github.com/catchorg/Catch2/pull/1971/files)

**Comment by ssandys** [comment]
I think the most consistent fix is to change line 14 of the formula from:

` patch :DATA  if MacOS.version == :big_sur || MacOS.version == :mojave || MacOS.version == :catalina
`
to

` patch :DATA  if MacOS.version == :monterey || MacOS.version == :big_sur || MacOS.version == :mojave || MacOS.version == :catalina`

**Comment by wmaciejak** [comment]
Exactly as @ssandys mentioned. If you want to use seabolt in Montery, you can use my fork
https://github.com/wmaciejak/homebrew-seabolt

**Comment by nomasprime** [comment]
@wmaciejak also fails at 98%

```
Last 15 lines from /Users/nomasprime/Library/Logs/Homebrew/seabolt/03.cmake:
[ 93%] Building CXX object CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DIS_BIG_ENDIAN=0 -DSEABOLT_STATIC_DEFINE -DUSE_OPENSSL=1 -DUSE_POSIXSOCK=1 -DUSE_WINSOCK=0 -DUSE_WINSSPI=0 -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/src -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/include/seabolt17/bolt -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/common/tests -O3 -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wall -Wextra -pedantic -Werror -fPIC -MD -MT CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o -MF CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o.d -o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o -c /tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests/test-warden.cpp
[ 94%] Building CXX object CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DIS_BIG_ENDIAN=0 -DSEABOLT_STATIC_DEFINE -DUSE_OPENSSL=1 -DUSE_POSIXSOCK=1 -DUSE_WINSOCK=0 -DUSE_WINSSPI=0 -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/src -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/include/seabolt17/bolt -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/common/tests -O3 -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wall -Wextra -pedantic -Werror -fPIC -MD -MT CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o -MF CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o.d -o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o -c /tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests/test-string-builder.cpp
[ 95%] Building CXX object CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DIS_BIG_ENDIAN=0 -DSEABOLT_STATIC_DEFINE -DUSE_OPENSSL=1 -DUSE_POSIXSOCK=1 -DUSE_WINSOCK=0 -DUSE_WINSSPI=0 -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/src -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/include/seabolt17/bolt -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/common/tests -O3 -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wall -Wextra -pedantic -Werror -fPIC -MD -MT CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o -MF CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o.d -o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o -c /tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests/test-direct-pool.cpp
[ 96%] Building CXX object CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DIS_BIG_ENDIAN=0 -DSEABOLT_STATIC_DEFINE -DUSE_OPENSSL=1 -DUSE_POSIXSOCK=1 -DUSE_WINSOCK=0 -DUSE_WINSSPI=0 -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/src -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/include/seabolt17/bolt -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/common/tests -O3 -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wall -Wextra -pedantic -Werror -fPIC -MD -MT CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o -MF CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o.d -o CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o -c /tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests/test-v3.cpp
[ 97%] Building CXX object CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DIS_BIG_ENDIAN=0 -DSEABOLT_STATIC_DEFINE -DUSE_OPENSSL=1 -DUSE_POSIXSOCK=1 -DUSE_WINSOCK=0 -DUSE_WINSSPI=0 -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/src -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/include/seabolt17/bolt -I/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/common/tests -O3 -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wall -Wextra -pedantic -Werror -fPIC -MD -MT CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o -MF CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o.d -o CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o -c /tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/src/seabolt/tests/utils/test-context.cpp
[ 98%] Linking CXX executable bin/seabolt-test
/usr/local/Cellar/cmake/3.26.0/bin/cmake -E cmake_link_script CMakeFiles/seabolt-test.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names "CMakeFiles/seabolt-test.dir/src/seabolt/tests/main.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/seabolt.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-address-set.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-addressing.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-chunking-v1.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-communication.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-connection.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-pooling.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-values.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-warden.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-string-builder.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-direct-pool.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-v3.cpp.o" "CMakeFiles/seabolt-test.dir/src/seabolt/tests/utils/test-context.cpp.o" -o bin/seabolt-test  -Wl,-rpath,/tmp/seabolt-20230316-51968-xhd1gv/seabolt-1.7.4/build/lib lib/libseabolt17.a /usr/local/opt/openssl@3/lib/libssl.a /usr/local/opt/openssl@3/lib/libcrypto.a -lssl -lcrypto
[ 98%] Built target seabolt-test
make: *** [all] Error 2
```
